#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Copyright 2002-2018, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
# -------------------------------------------------------------------------- #

ONE_LOCATION=ENV["ONE_LOCATION"] if !defined?(ONE_LOCATION)

if !ONE_LOCATION
    RUBY_LIB_LOCATION="/usr/lib/one/ruby" if !defined?(RUBY_LIB_LOCATION)
else
    RUBY_LIB_LOCATION=ONE_LOCATION+"/lib/ruby" if !defined?(RUBY_LIB_LOCATION)
end

$: << RUBY_LIB_LOCATION
$: << File.dirname(__FILE__)

require 'az_driver'
require 'opennebula'

deploy_id = ARGV[0]
host      = ARGV[1]
vm_id     = ARGV[-2]


TERMINATE_STATES = ["SHUTDOWN", "SAVE_SUSPEND"]

begin
    vm_one = OpenNebula::VirtualMachine.new_with_id(vm_id, OpenNebula::Client.new)
    vm_one.info
    lcm_state = vm_one.lcm_state_str


    opts_credentials = AzDriver.host_credentials_with_name(host)
    client = AzDriver::Client.new(opts_credentials)

    opts = {
        gname: host,
        name: deploy_id,
        client: client
    }

    az_vm = AzDriver::VirtualMachine.new(opts)

    if TERMINATE_STATES.include? lcm_state
        nics = az_vm.nics

        az_net = AzDriver::Network.new(opts)
        disk = az_vm.diskname

        az_vm.delete
        az_vm.delete_disk(disk)
        nics.each do |nic|
            az_net.delete_nic(nic)
        end
    else
       az_vm.poweroff
    end

rescue => e
    OpenNebula.handle_driver_exception("Shutdown", e, host, deploy_id, vm_id)
end

